In [1]:
import numpy as np
import pandas as pd

In [2]:
#membacan data
file_path = 'data/customer_segmentation_dataset.csv'

data = pd.read_csv(file_path)
data

,customer_id,umur,penghasilan_juta,spending_score,segment_label
0,0668fc97-97cf-4d31-8cee-5f6aa3ead634,38,13.43,7.83,high
1,2a04cd5f-b0f4-4770-96d6-0cd1d97ce40a,20,3.71,3.71,low
2,c8b7ed92-61bc-457d-88c5-9f70d78498fc,37,23.04,7.10,high
3,97cd4f83-07d0-4f29-9dab-7a170de45fb8,21,2.20,3.41,low
4,34139432-4ba0-4eae-8e56-dab108e6881b,41,25.17,9.10,high
...,...,...,...,...,...
995,cc33739e-40ea-485a-b962-81fecb0e234e,40,18.33,7.17,high
996,e314940a-fd0f-4e5a-9997-2b7fb4034cb6,33,6.47,7.09,middle
997,f65845a7-72c5-413c-a1dd-75330070306f,59,15.69,9.36,high
998,b1934f5f-6f3e-4074-b129-c931640b3998,20,3.34,3.53,low
999,22348d03-e49a-427a-b7da-0a646f1e07f9,38,11.76,5.53,middle

In [3]:
data.describe()

              umur  penghasilan_juta  spending_score
count  1000.000000       1000.000000     1000.000000
mean     36.296000         11.030930        5.872650
std      12.926774          8.256995        2.461571
min      18.000000          1.500000        1.020000
25%      26.000000          3.910000        4.080000
50%      35.000000          8.510000        5.975000
75%      44.000000         17.517500        7.840000
max      65.000000         29.910000        9.990000

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   str
 1   umur              1000 non-null   int64
 2   penghasilan_juta  1000 non-null   float64
 3   spending_score    1000 non-null   float64
 4   segment_label     1000 non-null   str
dtypes: float64(2), int64(1), str(2)
memory usage: 39.2 KB

In [28]:
#mengambil data untuk dicluster dan diubah ke numpy
# datas_points = data[["umur", "penghasilan_juta"]].values
datas_points = data[["umur", "penghasilan_juta"]].to_numpy()
print(datas_points)

[[38.   13.43]
 [20.    3.71]
 [37.   23.04]
 ...
 [59.   15.69]
 [20.    3.34]
 [38.   11.76]]

In [35]:
#centroid atau titik
centroids = np.array([
    [20, 3.71], 
    [37, 23.04],
    [41, 25.17]
])

In [59]:
# membuat algoritma k-means
# fungsi untuk menghitung jarak
def distance(p, c):
    return ((p[0] - c[0])**2 + (p[1] - c[1])**2) **0.5 


# fungsi untuk mencari cluster
def k_means(datas, centroid):
    # data dan centroid
    poitns = datas.copy()
    old_c = centroid.copy()

    # memulai mencari distance atau jarak
    status = True
    while(status):
        # membuat cluster dari panjang centroid
        K = len(old_c)
        klusters = []
        for k in range(K):
            klusters.append([])

        # hitung jarak ke setiap centroid
        for point in poitns:
            # simpan semua jarak
            all_distances = []

            for c in range(len(old_c)):
                titik = old_c[c]

                #hitung jarak
                distances = distance(point, titik)
                print(distances)

            

        status = False

In [60]:
k_means(datas_points, centroids)

20.456744609052535
9.661889049249117
12.117243911055024
0.0
25.741967679258707
30.025515815719135
25.741967679258707
0.0
4.53176566031387
1.8111046352985791
26.273667425770615
30.456869504267836
30.025515815719135
4.53176566031387
0.0
12.79159489664991
15.716551784663197
19.261902813585163
0.1200000000000001
25.83219889982268
30.111399834614133
1.198165264060013
24.587982837150346
28.855502074994295
4.436935879635855
24.911091907020054
28.90716866107783
32.53398377082032
7.038636231543721
2.5303161857759973
31.483152637561567
6.576473218982953
5.300650903426859
33.51256629982252
8.09219376930632
3.567197779770558
23.151017256267597
17.735729474707263
18.92597157347543
31.418225602347437
5.883026432033091
1.3931618714277239
1.4645477117526762
27.20588171701112
31.489695139839
10.726341407954532
16.96179530592207
20.737801233496285
25.064000079795722
19.278267557018705
20.07259076452265
40.31007938468988
21.807668376055243
18.792554376667372
25.73581356786686
15.452132538908666
15.862613277767318
6.659737232053529
19.780636996820906
23.871424339573874
17.291200074026094
16.169999999999998
18.732058082335747
48.07099021239317
26.08956879674327
22.000020454535946
18.57284038589682
11.85
14.540990337662702
2.6840454541605663
25.904717717049145
30.026030373660785
31.8207495197709
6.563200438810322
2.0690335908341355
31.102951628422662
10.729962721277275
8.499435275358007
6.044245196879425
22.878015648215644
26.784250969552986
0.33000000000000007
25.99068294600971
30.262255368693193
24.062271297614444
18.940960904874913
19.95677579169541
21.22033223114096
16.764199951086244
18.410000000000004
8.00015624847415
21.36783564144951
25.133246905244853
41.379571046592545
22.677080940897135
19.550368282976155
2.197293790097264
25.192411555863405
29.34990459950424
48.08440911563747
26.09206967643617
22.000081818029678
6.02336284811068
21.781643647805826
25.750046601899577
25.464202324046987
16.551740089791164
17.094572237994143
11.211819656059403
15.885452464440538
19.73910079005627
44.9721024636385
28.802793267320446
26.016640828515893
1.156027681329474
25.991585176745186
30.331079769767513
12.119818480488888
18.325307637254006
21.71307440230425
1.0000499987500624
26.420363358591416
30.74021632975279
40.64043429886054
23.375414434828745
20.60584625779781
24.298971171636055
6.2913353113627615
7.724998381876853
13.47902444541147
13.006598325465424
16.937204609970326
29.989799932643766
4.50848089715372
0.05000000000000071
38.33548747570585
18.374332640942363
15.161543457049483
8.554583566720241
18.61961331499663
22.553600599460832
7.02157389763862
22.253413221346516
26.085246788175112
1.004041831797859
26.478980342905952
30.796144239173838
2.033937068839643
26.841788315982228
31.205578027013058
2.009975124224178
24.62561471313965
28.812420932646393
7.01643784266632
22.19090128859123
26.02620986620987
18.18967839187928
16.73989545964968
19.0773583076903
16.557403178034892
15.103142057201211
17.91200714604592
26.194419252963026
1.7286121600868138
5.051574012127309
2.23606797749979
27.826406523300847
32.14734203631772
1.9208331525668751
26.376900879367916
30.55503231875234
4.330773602949016
24.689675980052876
28.697289070572502
5.004408056903434
22.573754672185128
26.600046992439694
2.0155644370746373
27.28326226828456
31.62790065748911
1.1510430052782565
25.998799972306415
30.33796466475627
4.0697051490249265
23.92083610578861
27.96934214456965
6.47715987142513
20.156192596817487
24.223137699315505
15.150194718220622
12.22303153886138
15.847472984674877
19.02810815609371
13.19793923307726
15.581530733531928
41.93149174546501
19.123516935961337
15.000053333238519
13.64275998469518
12.758824397255415
16.712034585890493
27.21102901398622
2.8604894686049795
5.030159043211258
34.903661699025214
13.085109858155567
9.700742239643315
2.1092415698539604
26.630726614195115
31.0036143054322
1.0846197490365
26.721947908039937
31.027961583062464
4.407096549884062
24.85140639883385
28.8505823164802
7.013194707121713
22.146277339543996
25.984073968490776
23.59157688667716
15.305110257688442
16.33291462048339
12.52039935465319
14.636341756053662
18.429064002276405
17.143048153697755
17.119999999999997
19.661192741031762
16.9021921655151
11.712028005430998
14.928794325061888
5.012235030403104
23.0499978308025
27.049512010385698
1.1661903789690602
26.85525833053929
31.155153666769163
3.0306599941266916
23.520416662976018
27.681417955010904
14.202538505492601
17.203592648048836
20.31415516333377
31.04345502678463
7.009251029889
3.4832312584725136
32.3996358004222
17.15249544526976
15.651249151425583
11.215150467113672
14.57946844024157
18.813824704190267
1.000199980003999
26.39841093702422
30.719270824679416
24.158178739300695
17.98790982854873
18.93911296761282
42.31978378961783
18.54431449258775
14.19256495493327
6.305838564378254
20.57697985614021
24.61768470023126
6.141343501221862
21.11209132227312
25.12016122559726
25.96077040459316
9.44161532789808
9.62997403942503
33.74268661502815
11.01135777277262
7.477760359893864
44.59498178046494
27.062891567606002
24.01935885905367
23.57171185976954
15.387946581659294
16.42224101637776
2.2922478051031048
25.361437262111153
29.510276176274598
3.3906341589738047
25.164023923053325
29.237674326115613
3.0028153456381563
23.762154784446633
27.910014331777045
24.875120100212584
14.58026405796548
15.218620173984238
0.7199999999999998
25.20579496861783
29.515209638422018
5.612708793443679
20.629309246797384
24.77071052674913
12.409093439893182
16.925392166800744
20.39338127922881
4.02095759738896
22.955748735338602
27.057392705136984
1.0283968105745953
24.908394167428778
29.159705073954367
12.333795036403028
17.221800138196937
20.67201248064639
15.345931056798085
16.213824348376296
19.182502443633368
17.012007524098973
13.586850260454039
16.457897800144465
35.539662350675194
9.958157460092705
5.517245689653486
11.341186004999654
15.6345898571085
19.50723199226379
1.0846197490365
26.721947908039937
31.027961583062464
18.830318637771374
13.836184445142381
16.210024676107068
23.14874510637672
17.754551529115005
18.94585970601493
7.021744797413247
18.74459922217597
23.00523636044629
45.63521556868117
21.823922653821885
17.421713463376673
3.13789738519283
24.618336661927426
28.720452642672612
24.252424621055933
17.31778276801046
18.218696440744605
45.34710575108405
26.46327455172545
23.105055723802096
15.552880762096777
15.350843625025954
18.358172567006772
1.3793114224133722
25.831732423513525
30.03677912160357
45.28939831792867
21.660934882871516
17.294866290318637
17.757164751164527
14.2
16.81276003516377
11.810588469674151
16.18335255748944
19.861158072982555
30.339678640354776
8.281280094284941
5.850888821367231
6.051784860683664
22.93064325307949
26.83398032346301
28.632850015323307
3.21645767887594
1.3931618714277263
40.2222873541523
18.00666820930513
14.095729849851692
8.101752896750185
22.489377492496317
26.193655720422075
2.878350221915325
28.6174771774173
32.903812848969345
47.57649104337141
25.18174735795751
21.01885106279599
35.323646470884064
17.357790758042913
14.91642048213981
17.26267650163207
16.33
18.88839855572727
1.0084145972763385
26.31805463935357
30.64259943281575
35.447088738004986
14.162612753302266
10.873495298201036
5.317527620990793
24.308426522504494
28.239916784579947
37.426569439370205
15.000213331816319
11.189392298065163
25.0
14.178466066539073
14.767924701866542
22.437649163849585
15.735513973175456
17.079300336957605
19.25123372669918
16.352764292314617
18.46861120929238
32.04272304283767
6.699283543782872
2.173131381210072
26.055356455055456
7.337363286630966
7.566372975210778
12.416766889975827
16.896733412112532
20.366465083563227
20.603145390934852
7.6899999999999995
10.60341454438145
28.542774917656484
2.8072940708091143
2.0063897926375125
15.840078913944842
14.379763558556864
17.434933323646526
4.132989232988637
24.164786363632516
28.20017730440715
28.17485581152102
4.942711806286099
6.458490535721174
20.04417371706801
18.24828759089466
20.15482324407734
18.697689696858273
14.304995630897618
16.672132437093946
44.933746783458865
26.750029906525338
23.556239088615147
20.055425699795055
18.09048368618153
19.995021880458147
43.14099674323717
23.21742664465638
19.725364381932213
12.148481386576679
13.739319488242495
17.913402803487674
23.589353530777394
15.31431030115297
16.342839410579792
30.307754783223388
13.444437511476632
12.092129671815465
2.2682372009999305
25.32113741521103
29.47203589845805
16.39586533245501
12.866394211277688
16.00704844748088
14.8268978549122
12.839003076563225
16.411852424391345
33.58023823620076
17.570500846589432
15.755583137415131
8.246211251235321
23.15100213813648
26.82110363128259
2.09990475974507
26.651756039705898
31.023739297512154
7.215434844830906
23.33166089244398
27.105425656130176
26.085520888032885
1.096585609973065
3.9568169025114126
32.056651415891835
6.708203932499369
2.1810318658836683
50.08991914547278
28.1270137056887
24.00607423132737
2.751744900967384
25.98631178139753
30.10352969337649
23.77731902465036
14.590750494748375
15.559077736164186
11.149547076002683
18.509459743601376
22.039274035230832
24.605698526967284
9.698252419895038
10.487783369234894
41.03754865973357
17.38742361593574
13.088559890224746
41.228632041337484
24.824093135500437
22.193713073751315
28.02519580663086
12.636332537568011
12.083045973594574
4.008441093492581
23.0795342240696
27.17425251961864
26.109402520931038
14.256226709757389
14.492925860570738
4.338478996146
24.70668128260046
28.713404535164408
30.322559258743315
6.01538859925109
2.6248809496813394
19.489371462415097
15.122833729165972
17.23642654380542
16.660207081546137
12.24444363783018
15.424788491256535
2.045702813216035
24.12902816111747
28.34185773727615
23.662493528789394
15.020416106087074
16.025292509030844
5.011546667447087
22.463750799899824
26.4963091769401
3.0053951487283666
23.72177269935786
27.871820894946925
44.23869912192265
20.596271507241305
16.241431587147726
46.71457588376459
28.811527207005184
25.604030932648087
20.659922555517966
14.4645255712035
16.310683615348562
25.7742681758377
15.315469303942336
15.707835624299104
1.664001201922643
27.401379527315772
31.67623872873798
2.0120636172845034
24.64147925754458
28.82745913187633
34.49517212596569
14.61642911247477
11.835070764469473
29.294588237420236
8.971265239641507
7.369945725716033
13.319534526401439
16.90990538116639
20.210729823536806
10.301461061422307
15.680102040484304
19.826772304134632
23.611490846619578
7.414067709429148
8.965941110669867
24.39460801078796
12.705904139414873
13.47920249866438
10.709547142619991
15.16852332957958
19.355505676680217
10.56542001058169
17.390986171002492
21.137703281104123
2.878350221915325
26.13350340080717
30.243361254992806
10.685391897352199
15.752615655820463
19.760819821049935
2.0591503102007875
27.456008449882148
31.793120325001134
15.220262809820335
16.868980407837338
19.810461882550847
10.656528515421895
15.232993796361896
19.414849986543807
7.007310468360882
22.048185866415402
25.891473499976783
7.029196255618419
21.1970776287676
25.089288551092874
1.1364858116140297
26.81076089931056
31.11269837220809
44.63227531730821
23.004801672694335
19.072377932497037
20.48224841173449
11.849995780589966
13.954071090545586
31.522537968888226
12.021751120365119
9.8853629169596
50.03295813761165
28.114971100821
24.00350182785837
8.154532482000423
22.764623871261303
26.45451946265515
1.9636954957426571
26.41666898002093
30.59285047196485
4.09140562643207
24.013248426649817
28.056771018775486
6.668440597321085
19.76401781015186
23.85586929877006
45.31379591250329
25.107417230770672
21.466310814855916
25.580781848880225
16.046435741310276
16.531231049138476
4.415529413331996
24.86845391253747
28.866743841313312
2.018142710513803
24.25455833446571
28.46078178827841
2.0436242316042352
24.80045362488356
28.97817109480859
19.122384788514218
17.28608978340677
19.403350226185168
37.014894299457346
11.656761986074866
7.134395559541116
19.089853325785402
17.594044446914417
19.711724937204256
15.983441431681728
13.95407109054558
17.031840769570387
8.005623023850173
21.05091209425378
24.834363289603385
8.00390529679106
21.0961228665364
24.876979318237172
5.042072986381693
23.306659992371277
27.291978675061287
12.976628992153548
13.089064137668514
17.174868267325955
8.365189776687675
17.820283387196735
21.930216597197578
10.823312801540942
15.032019159114984
19.229895995558582
33.1866855832275
13.979256060320234
11.569481405836653
23.359803081361793
2.517161099333929
6.686822862914795
11.370417758376338
14.40702953422391
18.65541208336069
48.59720259438809
24.933864521970918
20.52892836949849
33.276754649454624
12.371746036837322
9.508922126087688
24.88831251812786
14.536423218935253
15.169604477375145
1.7286121600868138
26.194419252963026
30.381522345004374
20.41204546340224
12.037312823051497
14.142135623730953
8.009019915070757
21.66758177554662
25.416246772487874
2.076920797719547
24.912087427592255
29.084023105478376
1.2621014222319855
24.50456284041811
28.77631143840364
9.893048064171122
16.233302190250754
20.337394130025608
29.964038446110695
7.136672894283442
4.624975675611713
20.223748416156685
16.60327979647395
18.48706574878772
13.450189589741848
13.050980806054387
16.977585222875486
1.7042300314218148
27.439098017245392
31.712231078875547
16.920664880553602
11.672617529928752
14.892175798049124
2.0002249873451734
24.491010595726753
28.68484094430367
40.07632842464489
19.077693780957908
15.48620353734252
33.61287848429527
13.652432017776173
10.985900054160334
31.92210676004953
10.261091559868278
7.458210241069906
1.1135977729862787
25.47218875558204
29.695159538214305
6.956320866665079
19.260220663325743
23.384687297460278
18.878667855545316
11.12
13.84061053566641
25.97391191176254
2.5737909783041806
4.25
48.97205733885396
28.00000178571423
24.095219442868746
9.418115522757192
16.947259365454936
20.998097532871878
25.007750798502453
3.6640005458514877
5.571355310873651
1.2806248474865696
27.004016367940526
31.297086126347292
24.772961066453078
14.932384270437188
15.610970501541539
22.351789637521197
16.172334401687344
17.538531865580996
48.39256141185337
26.1579223181047
22.012441936323192
7.280109889280518
23.55777790879267
27.31980234189113
13.656881049492963
13.751221763901562
17.441433427330452
8.000624975587845
21.41319453047583
25.176052113069677
2.0615528128088303
24.074237267253142
28.289955814741035
2.297150408658519
25.36950137468216
29.517928450350308
6.077902598758884
23.088741845323664
26.98341898277533
1.6800000000000002
27.026285353337034
31.24835355662759
24.755704393129275
14.994252232105474
15.679671552682475
23.15810009478325
6.41
8.459810872590477
14.301104852423116
13.955532952918709
17.44276354251241
15.243388730856404
13.634148304899721
16.943579905084995
17.97887649437528
11.17483333209046
14.171365495251333
13.753548632989233
15.36963239638476
18.761154015678247
20.103770790575584
17.548336103460066
19.44572960832275
23.24413044189866
17.05992086734285
18.21016199818113
8.064762860741784
22.251348273756353
25.968257546473925
44.752681483906635
22.155459823709368
18.00666820930513
41.932718728935285
21.06086417980041
17.404393123576586
13.217094990957733
14.668472994828056
18.28787576510733
28.896755873281
4.033658389105354
1.610000000000003
44.05961870012041
22.031089396577737
18.025581821400383
30.52249170693638
5.413169127230369
4.379052408912227
19.060703030056366
17.92194464894923
20.040049900137475
1.12712022428843
26.034901574617102
30.372415116351878
10.358088626768938
18.043195393277767
21.747128546086262
21.54158768521949
15.070530846655666
16.660000000000004
2.0690335908341364
24.05077961314352
28.267736025369985
16.519273591777576
12.570127286547258
15.72932293520608
0.04999999999999982
25.70444319568117
29.989799932643766
43.29621807964294
21.047954770000814
17.014820010802346
28.165384783453607
12.379418403139947
11.747208178967462
22.10578204904771
17.88320161492343
19.32588937151406
38.53650866386315
19.802434193805567
16.865470642706654
47.6305794631978
28.24603334983516
24.70268204062061
7.529734391065863
18.212358441453976
22.50752985114093
24.167449182733375
17.914242936836597
18.860127253017144
15.165384927524919
13.82931668593933
17.125913114342257
2.3853720883753127
28.04633487641478
32.35765133627594
1.0965856099730655
24.747816065261194
29.00724219914744
17.080995287160523
13.387400793283213
16.2674644613105
33.990188290152204
11.000163635146524
7.334582469370701
25.07828542783577
19.10556201738122
19.886437589472884
13.088559890224746
18.253659906988513
21.484962182885035
20.59231895634875
11.564259595840971
13.667128447483035
8.076639152518824
22.333687559379886
26.046207017529444
27.97324435956616
12.734995092264464
12.210634709137771
5.3595615492314295
24.412857268251088
28.338879653225533
42.680674783794124
18.189582183216853
13.705312838457939
14.539742088496618
12.192391069843518
16.017568479641348
1.0384603988597736
26.20882484965703
30.53837585727178
31.226144494637822
5.503489801934769
1.6499999999999986
7.337574531137657
23.73901640759364
27.4917369403972
0.5899999999999999
26.187905605450773
30.450000000000003
8.009500608652203
20.969587501903796
24.757724047254424
13.16313412527579
14.790753868549094
18.40115485506277
6.383760647142091
20.374555209868998
24.427820205658957
1.2682271089990151
26.98911076712236
31.282864318984604
34.829579383047395
17.97431778955741
15.827267610045647
26.920670496850555
2.5263412279421007
5.003608697730069
34.18971190285171
14.836040576919437
12.229538012533428
2.150372060830404
26.546781349157943
30.923274406181505
9.288616689260033
17.159606638848107
21.194989974048113
1.59298462013919
27.33358556794187
31.61154852265229
2.02869416127715
24.736792435560435
28.917814578560392
29.558296635631763
8.75634626999184
6.955292948539264
19.604308199985024
14.637281168304447
16.749832834986744
29.832266088917883
4.570732982793898
3.798539192900343
44.94441010848846
21.51299374796544
17.18870559408125
4.173260116503643
24.29136472082209
28.32000176553667
8.724127463534677
18.22697177262312
22.187392816642518
17.87514755183856
11.403929147447384
14.386802980509605
7.261191362304123
20.06888138387389
24.02958384991301
10.307764064044152
15.671914369342373
19.819222991832955
6.334106093206839
24.026019229160706
27.870775016134733
32.44475920699674
8.113106679934635
4.0753404765737065
50.10750043656139
28.1308389494519
24.007007310366696
30.316043607304696
6.497414870546595
6.588178807530955
9.618503002026875
16.634906071270734
20.708800061809473
32.73545478529358
14.415717117091331
12.28371279377697
28.325564425091336
12.101574277754114
11.377539277014167
4.013589415971693
23.021728866442675
27.1196773579628
39.836887428613196
17.060038100778087
13.018832512940628
48.52855757180508
27.02405595020851
23.021296662004076
1.3900000000000001
26.80146264665419
31.03421498926628
16.055182963765937
18.027756377319946
20.74167061738278
39.4361509277972
19.272594532132928
15.928891989087
18.512765865747884
8.71265745912233
12.189015546794582
18.546722082351913
14.893609367779188
17.25282875356966
16.440586972489758
12.75774274705365
15.905121816572173
2.6509620895063737
28.371550891694305
32.668639396216065
8.238986588167261
23.123364807051765
26.79486704576084
20.753110610219373
14.112551151368768
15.951376116185088
6.284655917391182
23.88388578100306
27.736057758809203
23.475306174787157
15.812555138243786
16.87890991740877
1.4284257068535275
25.886724396879572
30.089041194428248
1.6480594649465776
26.115313515253845
30.30631782318664
2.4074052421642684
25.539164042701163
29.678948768445288
18.175544008364646
16.839717931129368
19.17612056699686
28.292827713044165
5.231787457456581
3.803800730848031
8.097215570799632
18.244659492574804
22.32514501632632
6.733505773369472
19.069147857206413
23.308850250494984
23.39666856627242
16.19264030354531
17.286089783406773
31.399428338745278
12.133194138395709
10.077822185373186
12.149485585818026
14.265514361564394
18.248112231132296
46.63039352182222
27.27878479698097
23.77478496222416
1.345362404707371
25.79249697101853
29.999493329054744
4.019950248448356